### ISSUE TITLE
Bug fixes and improvements for qa_package and qa_attributes

### ISSUE THREAD

**Issue by emilyodean** [NCEAS/datamgmt#145]
I had several open tickets for issues here, so I am going to consolidate them all into one. I think other issues arose as I was out, too.

**Bugs**
- [x] reading in public xlsx and xls fails because it attempts to do it by url
- [x] qa_attributes fails on private xlsx reads because dataone::getObject() fails. One option is to just skip over trying to download the object if it's a private xlsx.
- [x] qa_attributes will process attributes incorrectly if csv has multiple header lines. Should check physical > dataFormat > textFormat > numHeaderLines to see if there are multiple header lines.
- [x] qa_attributes tries and fails to read .Rmds and .ipynb

**Improvements**
- [x] Add unit tests for qa_attributes and qa_package
- [x] This function is pretty SASAP specific right now and apparently breaks on ADC packages. Future iterations should be more flexible.
- [x] Add support for spatial data

I am closing #90, #91, #92, and #119 since this captures all of them.

**Comment by drkrynstrng** [comment]
Another improvement for `qa_package` is to add support for spatial data and related attributes. In EML spatial data is stored as a spatialVector element, as opposed to a dataTable element. Spatial data should be stored inside a `.zip` file for most data packages, but it gets a little tricky from there because the spatial data could ultimately be in different formats, like a `.gdb` file or a `.shp` file. Downloading and reading the spatial data is easy enough using the `sf::st_read` function, but after that the data does not pass the call to `qa_attributes`. So it seems `qa_attributes` needs to be updated to support spatial data too. I'll pass this on to someone who has a better understanding of spatial data.

**Comment by drkrynstrng** [comment]
I have added support for spatialVector entities. I am now working on modularizing these functions (#159) and will add unit tests as I do that.

**Comment by jagoldstein** [comment]
It would be great to have an option in `qa_package()` to skip _specific_ troublesome data object PIDs.
