### ISSUE TITLE
Update edit_attribute to modify otherEntities 

### ISSUE THREAD

**Issue by dmullen17** [NCEAS/datamgmt#147]
The `edit_attribute` function only modifies `dataTable` objects in EML, when it should be able to modify `dataTable` or `otherEntity` objects as both can contain attribute metadata.   One way to go about this would be replacing the `dataTableNumber` with something like `object`, and having the user specify the path as an input (for instance `object = eml@dataset@dataTable[[2]]`)

**Comment by drkrynstrng** [comment]
@dmullen17 Currently `edit_attribute()` requires an EML object input and returns the entire modified EML object. We can change the input to only the data object (`object = eml@dataset@dataTable[[2]]`) and return only the modified object, instead of returning the entire EML object. In this case, it would then be necessary to assign the returned data object to the EML object:
```
new_object <- edit_attribute(eml@dataset@otherEntity[[1]], 2, attributeName = "new name", missingValueCode = "NA", missingValueCodeExplanation = "Data unavailable")
eml@dataset@otherEntity[[1]] <- new_object
```

This change would simplify the function somewhat and make it similar to how other EML elements are modified. `edit_attribute()` doesn't seem to be called by any other function in datamgmt or arcticdatautils, so I think it would be fine to change the return object. Some data processing scripts might break though.

**Comment by dmullen17** [comment]
Sounds like a great idea!  Just to clarify I think the intent of the function is to edit attributes, not entities.  So the input should be something like: 
```
eml@dataset@dataTable[[1]]@attributeList@attribute[[1]] <-  edit_attribute(eml, entityIndex = 1, type = 'dataTable`, attributeIndex = 1,  attributeName = NULL ... etc.)
``` 
The defaults for entity_index and attribute_index and type are 1, 1, and `dataTable` respectively, but the indices can be changed to any valid index number / and type can be changed to `otherEntity`. 

Alternatively we could reduce the number of arguments and just pass the object in as the first argument: 
```
eml@dataset@dataTable[[1]]@attributeList@attribute[[1]] <-  edit_attribute(eml@dataset@dataTable[[1]]@attributeList@attribute[[1]],  attributeName = NULL ... etc.)
```  

What do you think?  I'd prefer the first version if i need to loop through something, but the second version is more straight-forward.

**Comment by drkrynstrng** [comment]
Yeah, I think the actual attribute should be the input then, to keep it simple and so that the input and output are of the same class. But I agree that the function should be easy to loop. We could still loop through it with that setup, but is there an advantage to having multiple arguments instead?

```
for (i in seq_along(eml@dataset@dataTable) {
  eml@dataset@dataTable[[i]]@attributeList@attribute[[1]] <- edit_attribute(eml@dataset@dataTable[[i]]@attributeList@attribute[[1]],  attributeName = "id")
}
```
or

```
eml@dataset@dataTable[[1]]@attributeList@attribute <- lapply(eml@dataset@dataTable[[1]]@attributeList@attribute, edit_attribute, missingValueCode = "NA", missingValueCodeExplanation = "data unavailable")
```
I wonder if one of these designs is better for use with the `map()` family of functions from the purrr package. I haven't used those extensively.

**Comment by dmullen17** [comment]
Keeping the input / output objects consistent is solid reasoning.  I think the advantage of multiple arguments is one less instance of unseemly EML objects like `eml@dataset@dataTable[[i]]@attributeList@attribute[[1]]`, but that's purely cosmetic.  I'd go with your structure in the above comment.
