### ISSUE TITLE
Harvest NSF award contact info

### ISSUE THREAD

**Issue by isteves** [NCEAS/datamgmt#52]
Write script to regularly harvest information about NSF awardees for outreach purposes

**Comment by isteves** [comment]
Related to: https://github.nceas.ucsb.edu/KNB/arctic-data/issues/258

**Comment by isteves** [comment]
https://nceas.github.io/oss-lessons/data-liberation/intro-webscraping.html

**Comment by mbjones** [comment]
@isteves The NSF site has an API so you should not have to scrape the site.

**Comment by isteves** [comment]
@jagoldstein want to take a look at the result?  https://github.com/NCEAS/datamgmt/blob/master/R/get_awards.R  I've customized it so that we can easily grab the newest awards using `from_date` (i.e. `get_awards(from_date = "01/01/2018)`).  You can play around with the other parameters a bit, but that's the key one!  I've built in the filter for programs with either 'polar' or 'arctic' in the name. To get all programs ever, you should be able to run `get_awards()` (but it might take some time)

**Comment by isteves** [comment]
@vlraymond let me know what you & Kathryn think! (slack me if you're unsure about how to test it out)

**Comment by jagoldstein** [comment]
@isteves this is looking great so far! Nice job.
`get_awards` seems to work well with specifying a date range, like so:
`get_awards(from_date = "01/02/2018", to_date = "02/20/2018")`
which is important here.

I like how it queries the `fundProgramName` for "Arctic" and "Polar". Ultimately, we may want to filter more precisely for these 5 programs:
- Arctic Natural Sciences Program (ANS)
- Arctic System Science Program (ARCSS)
- Arctic Social Sciences Program (ASSP)
- Arctic Observing Network (AON)
- Polar Cyberinfrastructure (ACI)
to truly automate the email notification process. But it also seems like that task may be very manageable manually (only 92 new awards in 2017). I am talking to you IRL right now and you are adding "AON" to the query since it's listed in the NSF API that way and not spelled out.
